trigger:
- master

pool:
  vmImage: windows-latest

steps:

# -------------------------------
# Use Python
# -------------------------------
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Use Python 3.12'


# -------------------------------
# Create venv & Install Dependencies
# -------------------------------
- script: |
    python -m venv .venv
    .venv\Scripts\python -m pip install --upgrade pip
    .venv\Scripts\python -m pip install -r requirement.txt
    .venv\Scripts\python -m playwright install
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Set up Virtual Env and Install Dependencies & Playwright Browsers'


# -------------------------------
# Run Pytest
# -------------------------------
- script: |
    .venv\Scripts\python -m pytest -v --alluredir=tests\allure-results
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Run Pytest'
  continueOnError: true


# -------------------------------
# Generate Allure Report
# -------------------------------
- script: |
    run_allure.bat
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Generate Allure Single HTML Report'


# -------------------------------
# Publish Allure Report
# -------------------------------
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'tests\allure-report'
    artifactName: 'AllureReport'
    publishLocation: 'Container'
  displayName: 'Publish Allure Report'